test: moved lint tests to appveyor_tests.sh

diff --git a/.appveyor.yml b/.appveyor.yml
--- a/.appveyor.yml
+++ b/.appveyor.yml
@@ -61,7 +61,8 @@ for:
       - sh: date
       - sh: pwd; ls -la; printenv
       - sh: PATH=$PATH:/home/appveyor/.local/bin
-      - sh: pip install --user salt-lint
+      - sh: ./scripts/appveyor_tests.sh -i
+      # - sh: pip install --user salt-lint
       # - sh: pip install --user yamllint>=1.17.0
       # - sh: gem install rubocop
       # - sh: sudo apt-get install shellcheck
@@ -74,25 +75,30 @@ for:
       #   eval "$({ berr=$({ bout=$(git ls-files -- '*.sls' '*.jinja' '*.j2' '*.tmpl' '*.tst' |
       #   xargs salt-lint); bret=$?; } 2>&1; declare -p bout bret >&2); declare -p berr; } 2>&1)"
       # - sh: Add-AppveyorTest -Name "Test A" -Framework NUnit -Filename a.exe -Outcome Passed -Duration 1000 # in milliseconds
-      - sh: test_name="salt-lint"
-      - sh: appveyor AddTest $test_name -Framework junit -Filename "*.sls *.jinja *.j2 *.tmpl *.tst" -Outcome Running
-      - sh: test_command="git ls-files -- '*.sls' '*.jinja' '*.j2' '*.tmpl' '*.tst' | xargs salt-lint"
-      - sh: start=`date +%s`
-      - sh: eval "$({ cerr=$({ cout=$($test_command); cret=$?; } 2>&1; declare -p cout cret >&2); declare -p cerr; } 2>&1)"
-      - sh: end=`date +%s`
-      - sh: cruntime=$((end-start))
-      - sh: if [[ -z cout ]]; then cout_safe="-StdOut $cout"; else cout_safe=''; fi
-      - sh: if [[ -z cerr ]]; then cerr_safe="-StdErr $cerr"; else cerr_safe=''; fi
-      - sh: if [[ -z cret ]]; then cret_safe="$cret"; else cret_safe=''; fi
-      - sh: echo "cout_safe $cout_safe"
-      - sh: echo "cerr_safe $cerr_safe"
-      - sh: echo "cret_safe $cret_safe"
-      - sh: >
-          if [[ "$bret" -eq 0 ]]; then
-            appveyor UpdateTest -Name $test_name -Framework junit -Filename "*.sls *.jinja *.j2 *.tmpl *.tst" -Outcome Passed -Duration $cruntime $cout_safe
-          else
-            appveyor UpdateTest -Name $test_name -Framework junit -Filename "*.sls *.jinja *.j2 *.tmpl *.tst" -Outcome Failed -Duration $cruntime -ErrorMessage "$test_name did not complete successfully: $cret_safe" $cout_safe $cerr_safe
-          fi
+      - sh: ./scripts/appveyor_tests.sh -t salt-lint
+      - sh: ./scripts/appveyor_tests.sh -t yamllint
+      - sh: ./scripts/appveyor_tests.sh -t rubocop
+      - sh: ./scripts/appveyor_tests.sh -t shellcheck
+      - sh: ./scripts/appveyor_tests.sh -t commitlint
+      # - sh: test_name="salt-lint"
+      # - sh: appveyor AddTest $test_name -Framework junit -Filename "*.sls *.jinja *.j2 *.tmpl *.tst" -Outcome Running
+      # - sh: test_command="git ls-files -- '*.sls' '*.jinja' '*.j2' '*.tmpl' '*.tst' | xargs salt-lint"
+      # - sh: start=`date +%s`
+      # - sh: eval "$({ cerr=$({ cout=$($test_command); cret=$?; } 2>&1; declare -p cout cret >&2); declare -p cerr; } 2>&1)"
+      # - sh: end=`date +%s`
+      # - sh: cruntime=$((end-start))
+      # - sh: if [[ -z cout ]]; then cout_safe="-StdOut $cout"; else cout_safe=''; fi
+      # - sh: if [[ -z cerr ]]; then cerr_safe="-StdErr $cerr"; else cerr_safe=''; fi
+      # - sh: if [[ -z cret ]]; then cret_safe="$cret"; else cret_safe=''; fi
+      # - sh: echo "cout_safe $cout_safe"
+      # - sh: echo "cerr_safe $cerr_safe"
+      # - sh: echo "cret_safe $cret_safe"
+      # - sh: >
+      #     if [[ "$bret" -eq 0 ]]; then
+      #       appveyor UpdateTest -Name $test_name -Framework junit -Filename "*.sls *.jinja *.j2 *.tmpl *.tst" -Outcome Passed -Duration $cruntime $cout_safe
+      #     else
+      #       appveyor UpdateTest -Name $test_name -Framework junit -Filename "*.sls *.jinja *.j2 *.tmpl *.tst" -Outcome Failed -Duration $cruntime -ErrorMessage "$test_name did not complete successfully: $cret_safe" $cout_safe $cerr_safe
+      #     fi
       # - sh: ./scripts/run_test.sh salt-lint
       # - sh: git ls-files -- '*.sls' '*.jinja' '*.j2' '*.tmpl' '*.tst' | xargs salt-lint
       # - sh: echo YAML LINT
